/*
 * This Java source file was generated by the Gradle 'init' task.
 * I left it because applications should be friendly.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        // I left this since I like applications to be friendly.
        System.out.println(new App().getGreeting());
    }
}
